### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by SConaway** [itzg/mc-server-runner#1]
How does this work? Can we please get a README with instructions?

**Comment by itzg** [comment]
Yes, I can certainly add at least that.

**Comment by itzg** [comment]
...in summary, it intercepts the `TERM` sent by docker during a `stop` operation and sends a literal "stop" command to the minecraft server to allow for it to gracefully shutdown.

**Comment by SConaway** [comment]
Is that it? It's written in Go and I have no idea about Go.

**Comment by itzg** [comment]
I finally added the beginning of docs here https://github.com/itzg/mc-server-runner/commit/fde5a96925eddcbff60880040205e0fe5ea75bb3

**Comment by SConaway** [comment]
Thanks.
