### ISSUE TITLE
Include a variable to allow for announcements during server shutdowns

### ISSUE THREAD

**Issue by ChipWolf** [itzg/mc-server-runner#10]
It would be good to have a small grace period to warn players to get to a safe point before the server stops, a configurable command and duration to wait before stopping would be ideal

**Comment by itzg** [comment]
Great idea. Just want to note to ourselves that the "stop grace period" would need to be altered for maximum benefit

https://docs.docker.com/engine/reference/commandline/stop/

**Comment by ChipWolf** [comment]
Hey, @itzg I'd like to implement this; could you please give me any pointers on how to architect it?
Thanks

**Comment by itzg** [comment]
Certainly. It would be pretty similar to and added just before the bit where the stop command is posted to the server:

https://github.com/itzg/mc-server-runner/blob/823ee3c58763b6545c2077ec5572d6d383fb7dd1/main.go#L146-L152

I'm thinking there could be a new string command-line arg added to

https://github.com/itzg/mc-server-runner/blob/823ee3c58763b6545c2077ec5572d6d383fb7dd1/main.go#L21-L30

I have some ideas for "handing off" the logic amongst that `select`, so if you get stuck at that point feel free to push what you have I can add to it.

https://github.com/itzg/mc-server-runner/blob/823ee3c58763b6545c2077ec5572d6d383fb7dd1/main.go#L143

**Comment by morrissimo** [comment]
I'm interested in this capability as well - have been experimenting with a [AWS Spot Instance version](https://github.com/vatertime/minecraft-spot-pricing) of your minecraft docker container and this would be hugely useful in that scenario!

**Comment by itzg** [comment]
Added by #12

**Comment by itzg** [comment]
Now available in https://github.com/itzg/docker-minecraft-server/releases/tag/2021.18.0

**Comment by ChipWolf** [comment]
Oh nice! Thanks for saving me the effort @morrissimo very much appreciated <3
