### ISSUE TITLE
Add option to save before shutdown

### ISSUE THREAD

**Issue by Ginotuch** [itzg/mc-server-runner#16]
Would be very nice to be able to configure this to run `save-all` before the server shuts down.

Today I was doing an apt upgrade which automatically restarted the docker containers (I didn't realise this before running an upgrade), this shut down the Minecraft container without saving first so a few minutes of progress in-game was lost.

**Comment by itzg** [comment]
The Minecraft server should already be doing that when the container is stopping -- that's really the main point of mc-server-runner, propagating the TERM signal into a `stop`. Perhaps the package upgrade process didn't allow enough time for the save to finish. It's hard to say without seeing the container logs.
