### ISSUE TITLE
Graceful shutdown not working if --no-console is set

### ISSUE THREAD

**Issue by Silthus** [itzg/mc-server-runner#3]
You `mc-server-runner` wrapper can only shutdown the server gracefully if `--no-console` is not set. Would it be possible to detect the use of `rcon-cli` and send the stop command over rcon if detected?

I am using [watchtower](https://github.com/v2tec/watchtower) and the `CONSOLE=FALSE` mode to run my servers. Unfortunatly if an update is available the servers are killed and plugins are not able to save their data.

As a workaround I enabled the console mode. Would be awesome if you could add this.

**Comment by itzg** [comment]
Ah yes, I forgot that there is the option for no console. Yes, I can have the wrapper pick up on the container environment variables (`ENABLE_RCON`, `RCON_PORT`, `RCON_PASSWORD`) to know when and how to authenticate rcon.

**Comment by itzg** [comment]
I need to do some testing now within the minecraft-server image.

**Comment by itzg** [comment]
@Silthus the latest minecraft-server image pushed to Docker Hub now uses this version that tries to use `rcon-cli` to stop the server.
