### ISSUE TITLE
mc-server-runner: Minecraft server process failed	{"exitCode": -1}

### ISSUE THREAD

**Issue by chazapp** [itzg/mc-server-runner#33]
Hi, I'm running a small Minecraft server for me and my friends. I have an issue where after a few hours, my server crashes with nothing more but this error:
```
<some player chat logs...>
2022-07-31T17:48:20.302Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": -1} 
2022-07-31T17:48:20.316Z	INFO	mc-server-runner	Done
```  
  
I'm running the server with 4Gb RAM on a k3s cluster. Here's the complete stack I've built:  
  - PaperMC + Geyser + Floodgate
  - itzg/minecraft-server + Prometheus scraping + Grafana dashboards +  everything configured in kubernetes
  - k3s 
  - Oracle Free tier ARM instances.

All my metrics are fine at the time of the crash. The tickrate is solid 20, and the memory consumption is under the limit. There is no apparent reason for the server to crash. k8s events don't mention killing the Pod. There is not Java stacktrace to show. 
Is there a way to make the mc-server-runner script more verbose ? What could be killing my Minecraft server process every few hours ?

For reference, here's my [Minecraft on k8s](https://github.com/chazapp/minecraft-k8s) repository.

**Comment by itzg** [comment]
mc-server-runner can't be any more verbose there -- it's just running the Java server process and all it gets is an exit code. 

Look at your system and kernel logs around that timeframe to see if there was an related system faults. Also, a kubectl describe on the pod might reveal a related event.

**Comment by chazapp** [comment]
TIL that `kubectl get events` does not return OOMKilled, but `describe` does. My Pod was indeed OOMKilled, even though my prometheus metrics didn't show an usage above the 4G limit. I have removed limits from my pod definition and do not get that crash anymore.  
Thanks for your help.
