### ISSUE TITLE
i686 release?

### ISSUE THREAD

**Issue by GoodOldJack12** [itzg/mc-server-runner#4]
I tried to compile the docker image on i686 but the executable downloaded from here does not have a i686 release. Any suggestions to remedy this problem?

**Comment by itzg** [comment]
To clarify, do you mean a 32-bit version of the build? If so, yes, I can update the build definition to add that variant and I'll bump the version in https://github.com/itzg/docker-minecraft-server .

**Comment by GoodOldJack12** [comment]
Yes, I do mean a 32bit build. The other wrappers would also need that though, since they also don't have 32 bit builds

**Comment by itzg** [comment]
Yes, I noticed that too and got 32 but builds created for them. Now I just need to bump the versions in the Dockerfile.

**Comment by itzg** [comment]
OK, the tool versions have been updated in the minecraft-server Dockerfile to support a `docker build --build-arg ARCH=386 ...` now:

https://github.com/itzg/docker-minecraft-server/commit/e6f593e8c47d791a22eae19e7570e6f35bf2308d
