### ISSUE TITLE
Tab Completion Support

### ISSUE THREAD

**Issue by remiscarlet** [itzg/mc-server-runner#61]
Hey there,

~~Not sure if this is even possible as I'm not sure if pipes are sufficient enough of a mechanism to support this.~~

## Request
Tab completion

## Description
Running 
- `java -jar paper.jar`
drops us into a prompt where we can tab-complete available commands:
![image](https://github.com/itzg/mc-server-runner/assets/2812190/87b2ac83-9fe8-466c-8565-1b1a0d61ae68)

However, running the equivalent `mc-server-runner` command
- `./mc-server-runner java -jar paper.jar`
does not support tab-completion.
![image](https://github.com/itzg/mc-server-runner/assets/2812190/058d3d3a-6f50-48f2-b21f-652a9405debd)

While sending full commands is supported with `docker attach`, it'd be useful to be able to leverage the graceful shutdown handling of this helper while also being able to have full console functionality.

## Extra Info
It doesn't quite operate the same as it does some extra things beyond just pipes, but fwiw I have successfully started a server with raw `java -jar` commands and used [reptyr](https://github.com/nelhage/reptyr) to successfully take over the IO with tab-complete working. Basically I'm not sure if tab completion needs something that reptyr does that goes beyond just redirecting pipes etc.

<subscript>btw thanks for all your work on these MC related images. They're awesome!</subscript>

**Comment by remiscarlet** [comment]
Going through the `itzg/minecraft-server` documentation again, I see auto-completion is expected to be supported as per the [Enabling Interactive Console](https://docker-minecraft-server.readthedocs.io/en/latest/commands/#enabling-interactive-console) page. I believe `mc-server-runner` is the mechanism by which that's done.

I followed the steps on that page as per below but still am not getting tab completion:
```
[Cirno(Remi)][~/tmp]> docker run \
    -d \
    -it \
    -p 26666:25565 \
    -v ./:/data \
    -e EULA=TRUE \
    --name mc \
    itzg/minecraft-server

[Cirno(Remi)][~/tmp]> docker attach mc
[18:12:56] [Server thread/INFO]: Done (14.346s)! For help, type "help"
[18:12:56] [Server thread/INFO]: Starting remote control listener
[18:12:56] [Server thread/INFO]: Thread RCON Listener started
[18:12:56] [Server thread/INFO]: RCON running on 0.0.0.0:25575
list
[18:13:00] [Server thread/INFO]: There are 0 of a max of 20 players online:
li
[18:13:01] [Server thread/INFO]: Unknown or incomplete command, see below for error
[18:13:01] [Server thread/INFO]: li     <--[HERE]
```

Where the last line shows the output of me typing `li<tab><enter>`

**Comment by itzg** [comment]
Resolved by #57

**Comment by itzg** [comment]
@remiscarlet make sure you have pulled the latest image. This is definitely working now.

**Comment by remiscarlet** [comment]
Oof, I must have had an unlucky cached image yeah. `docker image rm`'ing and repulling shows this working now.

Thanks!

**Comment by itzg** [comment]
I just noticed that vanilla minecraft may not actually support tab completion, but `TYPE=PAPER` definitely does.
