### ISSUE TITLE
MC Server Runner using high amount of memory, causing issues with quotas set and passed to java.

### ISSUE THREAD

**Issue by sfxworks** [itzg/mc-server-runner#8]
Relates to https://github.com/mcserverhosting-net/mc-operator/issues/3 

In a nutshell, I have an operator that sets the memory limit of a k8s deployment to match the java args of the server. `-Xmx` to match` resources.limits.memory.

The problem is, mcserverrunner uses ~100 MB of memory on idle. So I'll need to do some magic that adds some extra room for this binary even though java 8u212 is used to make java respect the overall memory limit of the container assigned. Though it assumes it is the only thing running in the container, leading to k8s killing it at it's last 100M because java is thinking it is free to use.

![image](https://user-images.githubusercontent.com/5921035/89613579-91018280-d850-11ea-929a-cd1c245c303e.png)

My plan is to eventually contribute a pr to https://github.com/itzg/docker-minecraft-server that separates the init process from the running process (using [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)) and work on having java/mc handle the SIGTERM directly between that and https://stackoverflow.com/a/31840306/5488621, but this will take time. Is there anything that can be done to mitigate the memory usage of this binary?

**Comment by sfxworks** [comment]
...It's entirely possible that I am reading this wrong since I completely forgot I was referencing VSZ there. Though it's still occurring and I'm trying to track that down.

**Comment by sfxworks** [comment]
Yeah, 8964 RES is not equal to 100 M. Something else is going on here...

**Comment by itzg** [comment]
I also wanted to note that the JVM process always requires more process level memory than just the heap setting, so it is incorrect to equate the two limits.
