### ISSUE TITLE
papermc

### ISSUE THREAD

**Issue by Tockra** [itzg/mc-server-runner#9]
Hi,

that seems to be exactly the program I need.
What I need to change, to use it with a PaperMC server?

T

**Comment by itzg** [comment]
It works without any changes for Paper (along with the various Java-based servers, Spigot, Bukkit, etc).

**Comment by Tockra** [comment]
Okay, then I didn't understand the usage maybe :p

**Comment by Tockra** [comment]
Okay after reading your readme again, I believe you didn't explain how to use your compiled go program? There is just a parameter list, which doesn't  contain a path to the java-server.jar

**Comment by itzg** [comment]
Ah, now I understand the confusion. I bet you're much more interested in my `itzg/minecraft-server` image which is documented here: https://github.com/itzg/docker-minecraft-server

(That image uses this `mc-server-runner` to manage the minecraft java process.)

**Comment by Tockra** [comment]
Okay, I found out when I build the Dockerfile correct the SIGTERM will be passed throw the PaperMC server and the successfully shutdowns. ;)

I had to use a 
`CMD ["java", "-jar", "stuff"]`
